version: "3.3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    ports: 
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
  
  wordpess:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test123
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpressvol:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "81:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  mariadbdata:
  wordpressvol: